### ISSUE TITLE
npm run prepublish => ReferenceError: Unknown plugin

### ISSUE THREAD

**Issue by damien916** [ethanselzer/react-image-magnify#1]
Hi,
I have an error when trying to run "prepublish" : 

> ReferenceError: Unknown plugin "'transform-es2015-modules-umd'" specified in "base" at 0, attempted to resolve relative to "src"
    at C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (C:\Node\forks\react-image-magnify\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Node\forks\react-image-magnify\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (C:\Node\forks\react-image-magnify\node_modules\babel-cli\lib\babel\util.js:59:12)

I have Node v6.9.5 on Windows 10

Do you know how to resolve the problem ?

Thank you

**Comment by ethanselzer** [comment]
Hi @damien916, I am not familiar with that error. Have you tried deleting the node_modules directory and running npm install?

**Comment by damien916** [comment]
Hi @ethanselzer, yes i tried, but it still not work.
Finally it's work by removing the plugin "transform-es2015-modules-umd" from prepublish command in package.json
Thank you

**Comment by ethanselzer** [comment]
@damien916 - I'm glad you found a workaround! Sorry for the trouble. If I were starting the project today, I probably would not support UMD/AMD modules, but because the package supports them today, I think it is best not to break that. Instead I think I will add a new command as an option for publishing to CommondJS only (`prepublish-cjs`). I will also add a section to the readme, explaining how to use the example project in development, and reference this issue. Thanks for opening this issue and raising my awareness to the problem!

```
"prepublish-cjs": "src --out-dir ./dist"
```

**Comment by ethanselzer** [comment]
@damien916 - I added the command `prepublish-csj`, as we discussed, and updated the [Development section](https://github.com/ethanselzer/react-image-magnify#development) of the readme with basic instructions on using the example project for development of react-image-magnify. It includes a link to this issue. Please have a look. Thanks!

**Comment by ethanselzer** [comment]
Closing with https://github.com/ethanselzer/react-image-magnify/commit/988a261dbae1f1d2aad52f1614550057b88998d0, which addresses this issue.

**Comment by damien916** [comment]
@ethanselzer Thank you, it's perfect :)
